##This function is to match the returned dbfIDs of each card, and then return the id
## of the string so that the cards a readable. Also we want to be able to write this function
## so we can organize the decklists that people are matching

##THIS FUNCTION IS SPECIFICALLY FOR MATCHING THE IMAGES FOUND IN THE SCHMICH LIBRARY
import json

def matchdbfidtoid(dbfid):
    """
    Takes in the dbfid, and the dictionary of cards that was generated by parsing
    through the hearthsims API which has a list of all the json files of each card
    """
    with open("finalmatchedid.json", "r") as fin:
        data = json.loads(fin.read())
        d = dict(data)
        cardID = d[dbfid]
    return cardID
