##This function is to match the returned dbfIDs of each card, and then return the name
## of the string so that the cards a readable. Also we want to be able to write this function
## so we can organize the decklists that people are matching
import json

def matchdbfid(dbfid):
    """
    Takes in the dbfid, and the dictionary of cards that was generated by parsing
    through the hearthsims API which has a list of all the json files of each card
    """
    with open("finalmatched.json", "r") as fin:
        data = json.loads(fin.read())
        d = dict(data)
        name = d[dbfid]
    return name


    
